import React from 'react';

function Content() {
  return (
    <div className="content">
      <p className="text">The discarded fragments of pre-modern manuscripts from the Cairo Geniza constitute a rich, still relatively untapped source for the history of the Mediterranean and Islamic world and its Jewish diaspora. This corpus of sacred and everyday texts, including documents such as personal letters and legal contracts, were preserved in an attic chamber of the Ben Ezra synagogue in Fustat, the medieval residential core of which later became part of the the city of Cairo.</p>
      <p className="text">Virtually all scholars who have studied these texts have come away with a transformed sense of the history of the region and the intimate ties that bound together its people. The Geniza corpus, which dates mostly from the 10th-13th centuries CE, is now widely recognized as the most important documentary source for reconstructing the lives of Jews and other inhabitants of the premodern Mediterranean. Thanks to the work of scholars and librarians over the last 120 years, almost one-quarter of the 350,000 items from the cache have been cataloged and nearly all have been digitized. Now that these fragments are digitally available and accessible, we need our community of volunteer humanists and historians like you to help us transcribe them. No matter your language ability, you can help us unlock this immense treasure-trove of fragments -- a task now ready to be scaled up thanks to people-powered research.</p>
      <p className="text">A geniza is a temporary storeroom or repository for old, used, and/or damaged Torah scrolls and other texts regarded as sacred in the Jewish tradition. The practice of not throwing away such documents is based on the sanctity imputed to them because they contain a written form of God’s name in Hebrew characters. Jewish custom dictates that these sacred writings be treated respectfully and buried when no longer in use. For reasons not entirely clear, Jews affiliated with the Ben Ezra synagogue kept their used texts in their Geniza chamber for nearly a millennium rather than burying them. There are similar practices of storing documents among Muslims and Christians across the Islamic world, as exemplified for example in the <a href="http://www.academia.edu/6120191/Geniza_for_Islamicists_Islamic_Geniza_and_the_New_Cairo_Geniza" target="_blank">Sana'a manuscripts</a> rediscovered in the attic of the Great Mosque of Sana'a during a 1972 renovation, but the Cairo Geniza is the largest cache of such stored documents.</p>
      <p className="text">The Cairo Geniza corpus includes both traditional religious, philosophical, and scientific texts (often termed the “literary” Geniza), and a wide range of everyday documents, such as letters, tax rolls, contracts, legal testimonies and other court documents, receipts, accounts and lists, known collectively as the “documentary” geniza. The survival of documents in the Cairo Geniza is of exceptional importance today because of what these fragmentary remains can teach us about the everyday lives of medieval Jews, Christians and Muslims and the relationships among them. The literary and documentary fragments together also offer unexpectedly fine-grained information about the historical context in which most of them were written and circulated: Cairo during the Fatimid and Ayyubid periods, one of the most important cultural and economic centers of its day.</p>
      <p className="text">Beginning in the Renaissance, European diplomats, scholars, and travelers to the Middle East and North Africa generated a vibrant antiquities market as they actively sought and purchased texts and artifacts to bring home with them for study or to add to their personal libraries. During the 19th century, the contents of the Cairo Geniza began to draw attention when assorted fragments began to come up for sale. Orientalists, traders, collectors, and scholars amassed these fragments for their own collections. Today, Cairo Geniza fragments can be found in collections from throughout the world. To learn about the history of the collections the fragments you are transcribing come from, <a href="#provenance">click here</a> or scroll down.</p>
    </div>
  );
};

export default Content;