name: Deploy Scribes of the Cairo Geniza to staging

on:
  # Run this workflow on push to master
  push:
    branches:
      - master

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build staging
    uses: zooniverse/ci-cd/.github/workflows/npm_build.yaml@main
    with:
      commit_id: ${{ github.sha }}
      node_version: 'lts/gallium'
      output: 'dist'
      script: 'build'
  deploy:
    name: Deploy staging
    uses: zooniverse/ci-cd/.github/workflows/deploy_static.yaml@main
    needs: build
    with:
      source: 'dist'
      target: 'preview.zooniverse.org/scribes'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}
  slack_notifiaction:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Build staging / build
      status: ${{ needs.deploy.result }}
      title: 'Scribes of the Cairo Geniza staging deploy complete'
      title_link: 'https://scribes.preview.zooniverse.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
